name: Build Images

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering
  pull_request:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        name: Checkout code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./services/cap-api
          file: ./services/cap-api/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rss-api-prod:latest,ghcr.io/${{ github.repository_owner }}/rss-api-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Database image
        uses: docker/build-push-action@v5
        with:
          context: ./services/cap-api/db
          file: ./services/cap-api/db/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rss-db:latest,ghcr.io/${{ github.repository_owner }}/rss-db:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: ./services/client
          file: ./services/client/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rss-client-prod:latest,ghcr.io/${{ github.repository_owner }}/rss-client-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push CAP Generator image
        uses: docker/build-push-action@v5
        with:
          context: ./services/cap-gen
          file: ./services/cap-gen/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cap-gen-prod:latest,ghcr.io/${{ github.repository_owner }}/cap-gen-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
