name: Build Images

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-images:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        name: Checkout code
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v.37.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
        with:
          context: ./services/cap-api
          file: ./services/cap-api/Dockerfile.prod
          push: true
          tags: ghcr.io/daniel-ibarrola/rss-api-prod:latest,ghcr.io/daniel-ibarrola/rss-api-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Database image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
        with:
          context: ./services/cap-api/db
          file: ./services/cap-api/db/Dockerfile
          push: true
          tags: ghcr.io/daniel-ibarrola/rss-db:latest,ghcr.io/daniel-ibarrola/rss-db:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Client image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
        with:
          context: ./services/client
          file: ./services/client/Dockerfile.prod
          push: true
          tags: ghcr.io/daniel-ibarrola/rss-client-prod:latest,ghcr.io/daniel-ibarrola/rss-client-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push CAP Generator image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
        with:
          context: ./services/cap-gen
          file: ./services/cap-gen/Dockerfile.prod
          push: true
          tags: ghcr.io/daniel-ibarrola/cap-gen-prod:latest,ghcr.io/daniel-ibarrola/cap-gen-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
